<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="EventStatistikData" Id="{ba717352-d74e-4e75-88d2-e77ef69424ec}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EventStatistikData
VAR_INPUT
	Count													:	INT; // eventclass counter Meldungen - Klasse
	Status													:	INT; // logicallink of eventclass-status
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[;]]></ST>
    </Implementation>
    <LineIds Name="EventStatistikData">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>