<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MMS_TO_MMIN" Id="{55954f0c-4287-420d-b6ab-b68be3713337}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION MMS_TO_MMIN : LREAL
VAR_INPUT
	IN														:	LREAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[MMS_TO_MMIN 												:= IN * 0.001 * 60;
]]></ST>
    </Implementation>
    <LineIds Name="MMS_TO_MMIN">
      <LineId Id="3" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>