<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FEED" Id="{5ff3d1d0-210e-41a5-9143-c2f89242d313}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM FEED
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FEED">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>