<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="AX_PARA_SET_ISTPOS" Id="{c2d12902-2957-4ada-852c-afb7b4c4641e}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'no_check'}
FUNCTION_BLOCK AX_PARA_SET_ISTPOS (* Datatyp - Set Istpos *)
VAR_INPUT
	Typ														: UDINT := 1; (* 0	NICHT DEFINIERT Wert wird nicht geschrieben
																			1	Absolutposition
																			2	Relativposition
																			5	Moduloposition *)
	Value													: LREAL;
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[;]]></ST>
    </Implementation>
    <LineIds Name="AX_PARA_SET_ISTPOS">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>